### ISSUE TITLE
Segfault https://github.com/pcwalton/font-kit/blob/master/examples/list-fonts.rs

### ISSUE THREAD

**Issue by jojolepro** [pcwalton/font-kit#5]
```
   Compiling font-kit v0.1.0 (/shareddata/share/Prog/Rust/font-kit)                                                                      
    Finished dev [unoptimized + debuginfo] target(s) in 34.28s                                                                           
     Running `target/debug/examples/list-fonts`
Loading fonts… 242 / 248 [====================================================================================>--] 97.58 % 142.13/s 0s zsh: segmentation fault (core dumped)  cargo run --example list-fonts
```

**Comment by jojolepro** [comment]
Cause by this line
```
Cell::new(&font.full_name()),
```

**Comment by pcwalton** [comment]
What OS?

**Comment by jojolepro** [comment]
Hi! Arch Linux x64 latest

**Comment by jneem** [comment]
I'm also running Arch x64, but can't reproduce this. Can you list your installed fonts?

**Comment by jojolepro** [comment]
Oh wow, this was a long time ago! I'm not sure if the bug is still present or not, but I will close this issue as it is really old and most likely fixed.

**Comment by indefini** [comment]
This is not fixed.
In my case it crashed with /usr/share/fonts/misc/decsess.pcf.gz
from xorg-fonts-misc on Arch.

```
#0  0x00007ffff7dbac95 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x00005555555ff40a in std::ffi::c_str::CStr::from_ptr () at src/libstd/ffi/c_str.rs:963
#2  0x00005555555e7624 in font_kit::loaders::freetype::Font::family_name (self=0x7fffffffd260)
    at src/loaders/freetype.rs:350
```

 `(*self.freetype_face).family_name)` is 0x0 so
` CStr::from_ptr((*self.freetype_face).family_name`
is crashing.

**Comment by indefini** [comment]
@pcwalton please reopen if that's alright
