### ISSUE TITLE
select_family_by_name_arial test fails on Windows 10

### ISSUE THREAD

**Issue by Songtronix** [pcwalton/font-kit#82]
```
---- test::select_family_by_name_arial stdout ----
thread 'test::select_family_by_name_arial' panicked at 'assertion failed: `(left == right)`
  left: `14`,
 right: `8`', tests\select_font.rs:116:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Program Files\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:211
   5: std::panicking::rust_panic_with_hook
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libstd\panicking.rs:339
   8: select_font::test::select_family_by_name_arial
             at .\tests\select_font.rs:116
   9: select_font::test::select_family_by_name_arial::{{closure}}
             at .\tests\select_font.rs:114
  10: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libcore\ops\function.rs:231
  11: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\liballoc\boxed.rs:766
  12: panic_unwind::__rust_maybe_catch_panic
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libpanic_unwind\lib.rs:82
  13: std::panicking::try
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libstd\panicking.rs:275
  14: std::panic::catch_unwind
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\src\libstd\panic.rs:394
  15: test::run_test::run_test_inner::{{closure}}
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320\/src\libtest\lib.rs:1466
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test::select_family_by_name_arial

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test select_font'
```

**Comment by RazrFalcon** [comment]
Those tests are for CI only. We cannot guarantee reproducible results on all OS'es.

**Comment by Songtronix** [comment]
Oh. Sorry for that, didn't know that. However I hit a ``PlatformError`` when using https://github.com/Aloxaf/silicon
Do you know how to debug a PlatformError? See https://github.com/Aloxaf/silicon/issues/5 for more information. Could it be a missing font or such?

**Comment by RazrFalcon** [comment]
This is a separate issue. Could you duplicate a one from `silicon`?

**Comment by Songtronix** [comment]
@RazrFalcon you mean copying the issue over here?

**Comment by RazrFalcon** [comment]
Yes. Create a new issue with the same backtrace. I've already reproduced it on my machine.
